"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-08 21:27:05.036266
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "salts",
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("salt", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("day", name=op.f("pk_salts")),
    )
    op.create_table(
        "targets",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("target_id", sa.String(length=512), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("fronts_target_pk", sa.Integer(), nullable=True),
        sa.Column("seed_source", sa.String(length=32), nullable=True),
        sa.Column("approved", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["fronts_target_pk"], ["targets.pk"], name=op.f("fk_targets_fronts_target_pk_targets")
        ),
        sa.PrimaryKeyConstraint("pk", name=op.f("pk_targets")),
        sa.UniqueConstraint("type", "target_id", name=op.f("uq_targets_type_target_id")),
    )
    op.create_table(
        "reports",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("target_pk", sa.Integer(), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("what_failed", sa.JSON(), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("agent_type", sa.String(length=32), nullable=True),
        sa.Column("note_scrubbed", sa.Text(), nullable=True),
        sa.Column("reporter_fp", sa.String(length=64), nullable=False),
        sa.Column("prefix_fp", sa.String(length=64), nullable=False),
        sa.Column("ua_family", sa.String(length=32), nullable=True),
        sa.Column("signed", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("options_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["target_pk"], ["targets.pk"], name=op.f("fk_reports_target_pk_targets")
        ),
        sa.PrimaryKeyConstraint("pk", name=op.f("pk_reports")),
    )
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_reports_reporter_fp_target_pk_created_at"),
            ["reporter_fp", "target_pk", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_reports_target_pk_created_at"), ["target_pk", "created_at"], unique=False
        )

    op.create_table(
        "status_current",
        sa.Column("target_pk", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("since", sa.DateTime(timezone=True), nullable=False),
        sa.Column("n_window", sa.Integer(), server_default="0", nullable=False),
        sa.Column("baseline", sa.Float(), server_default="0", nullable=False),
        sa.Column("breakdown", sa.JSON(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["target_pk"], ["targets.pk"], name=op.f("fk_status_current_target_pk_targets")
        ),
        sa.PrimaryKeyConstraint("target_pk", name=op.f("pk_status_current")),
    )
    op.create_table(
        "status_transitions",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("target_pk", sa.Integer(), nullable=False),
        sa.Column("from_status", sa.String(length=16), nullable=False),
        sa.Column("to_status", sa.String(length=16), nullable=False),
        sa.Column("inputs", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["target_pk"], ["targets.pk"], name=op.f("fk_status_transitions_target_pk_targets")
        ),
        sa.PrimaryKeyConstraint("pk", name=op.f("pk_status_transitions")),
    )
    with op.batch_alter_table("status_transitions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_status_transitions_target_pk_created_at"),
            ["target_pk", "created_at"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("status_transitions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_status_transitions_target_pk_created_at"))

    op.drop_table("status_transitions")
    op.drop_table("status_current")
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reports_target_pk_created_at"))
        batch_op.drop_index(batch_op.f("ix_reports_reporter_fp_target_pk_created_at"))

    op.drop_table("reports")
    op.drop_table("targets")
    op.drop_table("salts")
    # ### end Alembic commands ###
